CREATE TABLE profiles
(
  id VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  picture VARCHAR(255),
  PRIMARY KEY (id)
);


CREATE TABLE sitedowns
(
  creatorId VARCHAR(255) NOT NULL,
  id INT AUTO_INCREMENT,
  siteNum VARCHAR(255) NOT NULL,
  siteName VARCHAR(255) NOT NULL,
  cause VARCHAR(255) NOT NULL,
  solved TINYINT,
  PRIMARY KEY (id),
  FOREIGN KEY (creatorId)
    REFERENCES profiles(id)
    ON DELETE CASCADE
);